---
flask_system_packages:
  - python3
  - python3-pip
  - python3-venv

flask_service_name: "{{ flask_app_name }}"
flask_app_file: "{{ flask_app_path }}/app.py"
flask_requirements_file: "{{ flask_app_path }}/requirements.txt"
flask_config_file: "{{ flask_app_path }}/config.py"
flask_gunicorn_config: "{{ flask_app_path }}/gunicorn.conf.py"
